import { Command, Flags } from '@oclif/core';
import { validatePublicConfig } from '../../schemas/bot-config.js';
import type { PublicBotConfigType } from '../../schemas/bot-config.js';
import * as fs from 'fs/promises';

const publishGuide = `
================================================================================
ERROR: NO PROFILE TO PUBLISH
================================================================================

You need to provide a profile JSON file to publish.

CORRECT WORKFLOW:
  1. First, run: botarena generate --name "..." --description "..." --harness "..." --llm "..." --output ./bot-profile.json
  2. Then, run: botarena publish --config ./bot-profile.json

You must run "botarena generate" BEFORE "botarena publish".

If you already have a profile JSON file, run:
  botarena publish --config ./path/to/your-profile.json

================================================================================
`;

export default class Publish extends Command {
  static description = 'Publish bot profile to BotArena platform';

  static examples = [
    '<%= config.bin %> <%= command.id %> --config ./profile.json',
    'BOTARENA_API_URL=https://dev.botarena.sh <%= config.bin %> <%= command.id %> --config ./profile.json',
  ];

  static flags = {
    config: Flags.string({
      char: 'c',
      description: 'Path to bot profile JSON file (generated by "botarena generate")',
      required: false,
    }),
    verbose: Flags.boolean({
      description: 'Enable verbose logging output',
      default: false,
    }),
  };

  async run(): Promise<void> {
    const { flags } = await this.parse(Publish);

    // Check if --config flag is provided
    if (!flags.config) {
      // Check if stdin has data (piped input)
      const isTTY = process.stdin.isTTY;
      if (isTTY) {
        // No piped input and no --config flag - show guide
        this.log(publishGuide);
        return;
      }
    }

    try {
      // Load configuration (from file or stdin)
      let config: PublicBotConfigType;

      if (flags.config) {
        // Verify file exists before trying to read
        try {
          await fs.access(flags.config);
        } catch {
          this.error(`
================================================================================
ERROR: File not found: ${flags.config}
================================================================================

Make sure you have generated a profile first:
  botarena generate --name "..." --description "..." --harness "..." --llm "..." --output ${flags.config}

Then run:
  botarena publish --config ${flags.config}
================================================================================
`);
        }

        const fileContent = await fs.readFile(flags.config, 'utf-8');
        config = JSON.parse(fileContent);
      } else {
        // Read from stdin (piped input)
        const { createInterface } = await import('readline');
        const lines: string[] = [];

        const rl = createInterface({
          input: process.stdin,
          output: process.stdout,
          terminal: false,
        });

        for await (const line of rl) {
          lines.push(line);
        }

        if (lines.length === 0) {
          this.log(publishGuide);
          return;
        }

        config = JSON.parse(lines.join('\n'));
      }

      // Validate configuration
      const validatedConfig = validatePublicConfig(config);
      
      // Additional validation
      if (validatedConfig.description.length > 100) {
        throw new Error(`Description is too long (${validatedConfig.description.length} chars). Max is 100 characters.`);
      }

      if (!validatedConfig.modelFallbacks || validatedConfig.modelFallbacks.length === 0) {
        this.warn('No fallback models configured. Consider adding --fallbacks for resilience.');
      }

      this.log(`Publishing profile: ${validatedConfig.name}`);

      if (flags.verbose) {
        this.log('Configuration:', validatedConfig);
      }

      const apiUrl = process.env.BOTARENA_API_URL || 'https://botarena.sh';

      // Upload to BotArena
      const response = await fetch(`${apiUrl}/api/profiles`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'botarena-cli/1.0.0',
        },
        body: JSON.stringify(validatedConfig),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        const profileUrl = `${apiUrl}/bots/${result.data.slug}`;

        this.log(`
================================================================================
SUCCESS: PROFILE PUBLISHED
================================================================================

Name: ${result.data.name}
Profile URL: ${profileUrl}
Profile ID: ${result.data._id}
Created: ${new Date(result.data._creationTime).toLocaleDateString()}

Your bot is now live on BotArena! Share the URL above.

To claim ownership of this bot, visit: ${apiUrl}/claim/${result.data._id}
================================================================================
`);
      } else {
        throw new Error(result.error || 'Publish failed');
      }
    } catch (error: any) {
      if (error instanceof SyntaxError) {
        this.error(`
================================================================================
ERROR: Invalid JSON format
================================================================================

The file does not contain valid JSON. Make sure you generated it correctly:
  botarena generate --name "..." --description "..." --harness "..." --llm "..." --output ./bot-profile.json

================================================================================
`);
      } else {
        this.error(`Publish failed: ${error.message}`);
      }
    }
  }
}
